default: com/gradescope/DoubleQueue/code/IDoubleQueue.java com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/gradescope/DoubleQueue/code/ListDoubleQueue.java
	javac com/gradescope/DoubleQueue/code/IDoubleQueue.java com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/gradescope/DoubleQueue/code/ListDoubleQueue.java

run:
	java Driver/DoubleQueueDriver.java

clean:
	rm -f *.class